---
title: limebois when?
timezone: America/New_York
collections:
  posts:
    title: posts
    output: true
    comments: true
  uploads:
    title: uploads
    output: true
email: limesayahi@gmail.com
description: 'the blog you should(nt?) read, boi comments: true

'
baseurl: 
url: http://emilsayahi.cf/
"//facebook": 
github: https://github.com/emilsayahi
twitter: https://twitter.com/limebois
markdown: kramdown
gems:
- jekyll-paginate

permalink: pretty

paginate: 10
paginate_path: "blog/page:num"
