---
title: limebois when?
timezone: America/New_York
collections:
  posts:
    title: posts
    output: true
    comments: true
  uploads:
    title: uploads
    output: true
email: limesayahi@gmail.com
description: 'the blog you should(nt?) read, boi

'
baseurl: 
url: http://emilsayahi.cf/
github: https://github.com/emilsayahi
twitter: http://cucc.nut.cc
markdown: kramdown
gems:
- jekyll-paginate
permalink: pretty
paginate: 10
paginate_path: blog/page:num
