---
title: emil @ day
timezone: America/New_York
collections:
  posts:
    title: posts
    output: true
    comments: true
  uploads:
    title: uploads
    output: true
email: limesayahi@gmail.com
description: 'the blog you should(nt?) read, boi

'
baseurl: /d
url: http://liech.ga/
github: https://github.com/emilsayahi
markdown: kramdown
gems:
- jekyll-paginate
permalink: pretty
paginate: 10
paginate_path: blog/page:num
