---
title: emil @ day
timezone: America/New_York
collections:
  micro:
    title: micro
    output: true
    layout: post
  posts:
    title: posts
    output: true
    comments: true
  uploads:
    title: uploads
    output: true
email: em@emsa.cf
description: 'the blog you should(nt?) read, boi

'
baseurl: "/d"
url: http://liech.ga/
twitter: https://twitter.com/emilsayahi
github: https://github.com/emilsayahi
markdown: kramdown
gems:
- jekyll-paginate
permalink: pretty
paginate: 10
paginate_path: blog/page:num
